blank_issues_enabled: false
contact_links:
  - name: 🐛 Bug Report
    url: https://github.com/hashicorp/terraform-cdk/issues/new?assignees=&labels=bug%2C+new&template=bug-report.md&title=
    about: "If something isn't working as expected 🤔 please file bug reports in the main terraform-cdk repository instead."
  - name: 🚀 Feature Request
    url: https://github.com/hashicorp/terraform-cdk/issues/new?assignees=&labels=enhancement%2C+new&template=feature-request.md&title=
    about: "If you have a suggestion (and maybe even want to implement it yourself 🙂) please submit your requests in the main terraform-cdk repository instead."
  - name: ❓ Question
    url: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47
    about: 🙋 For usage questions that may not require a core maintainer to answer, post in our community forum
  - name: 💼 Terraform Cloud/Enterprise Troubleshooting
    url: https://support.hashicorp.com/hc/en-us/requests/new
    about: For issues related to the Terraform Cloud/Enterprise platform, please submit a HashiCorp support request or email tf-cloud@hashicorp.support
