# NOTE: Make sure you set up GitHub Branch Protection rules before adding this workflow
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
#
# You probably want to have the following requirements checked:
# - Require a pull request before merging
# - Require approvals (1)
# - Require status checks to pass before merging
# - Require conversation resolution before merging
# - Require linear history
# - Do not allow bypassing the above settings

name: automerge
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - ready_for_review
      - reopened
      - synchronize
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Turn on automerge for this PR
        run: gh pr merge --auto --squash ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
