# NOTE: Make sure you set up GitHub Branch Protection rules before adding this workflow
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
#
# You probably want to have the following requirements checked:
# - Require a pull request before merging
# - Require approvals (1)
# - Require status checks to pass before merging
#   - You need to have at least one status check marked as required from "any source". This should probably be your build or test workflow.
#   - I would not recommend turning on "Require branches to be up to date before merging" since it gets obnoxious
# - Require conversation resolution before merging
# - Require linear history
# - Do not allow bypassing the above settings
#
# NOTE: Before activating this workflow, it is recommended that you create a new label in your repo:
# - "automerge", suggested color: #5DC8DB

name: automerge
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - ready_for_review
      - reopened
      - synchronize
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Turn on automerge for this PR by trusted users
        if: github.event.pull_request.user.login == 'team-tf-cdk' || contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) || github.actor == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # NOTE: Replace this with the name of your token associated with the team-tf-cdk user
        run: gh pr merge --auto --squash ${{ github.event.pull_request.number }
